### ISSUE TITLE
Instead of opening my default macOS browser, opens Ubuntu VM through Parallels with Chromium

### ISSUE THREAD

**Issue by felixfbecker** [ExiaSR/better-opn#12]
Ever since Storybook changed to use `better-opn` my default browser doesn't open anymore when I run it, but instead an _Ubuntu VM_ boots up in Parallels to launch Chromium. This is extremely annoying of course as it takes a lot of resources and takes a while to shut down again.

Here's my setup:

I am on macOS Catalina and have Parallels installed.

Inside Parallels, I have a Ubuntu VM:

![image](https://user-images.githubusercontent.com/10532611/95680137-a93aa880-0bd7-11eb-82cd-b30d89abffb5.png)

Inside that Ubuntu VM, I have Chromium installed. This Chromium is registered in macOS as an app shortcut through Parallels:

![Chromium shortcut](https://user-images.githubusercontent.com/10532611/95680155-c1aac300-0bd7-11eb-8d94-262f90426fb8.png)

This is NOT my default browser though. I use regular Chrome, and sometimes others for development, and have [Choosy](https://www.choosyosx.com/) set as my default browser:

![Choosy default browser](https://user-images.githubusercontent.com/10532611/95680112-6a0c5780-0bd7-11eb-8cc7-f769a5135dd1.png)

I would expect that `better-opn` will always respect the choice I made in macOS system settings as my browser (i.e. exactly what would be picked if you run `open https://github.com` on the command line).

But instead it **always** tries to launch Chromium for some reason, which is inside a VM and **not my default browser**.

**Comment by ExiaSR** [comment]
the purpose of building this utility program is to re-use the same tab if possible and it is only possible with chromium and macOS, hence by default `better-opn` favours opening the URL in chromium-based browsers.

I suggest setting the `BROWSER` environment variable globally or on a per-project basis to the browser of your choice if you don't want such behaviour.

Learn more at https://github.com/storybookjs/storybook/issues/12206#issuecomment-679013491
