### ISSUE TITLE
Contribute the features back to upstream `open`?

### ISSUE THREAD

**Issue by karlhorky** [ExiaSR/better-opn#2]
Hey, thanks for creating this package, looks good!

Would you be amenable to opening an issue / pull request in [the `open` package](https://github.com/sindresorhus/open) (renamed from the original name `opn`) to add these features to upstream?

I searched for issues or PRs opened under your name in the project but didn't find anything yet.

**Comment by ExiaSR** [comment]
@karlhorky Hi, sorry for the late reply.

The incentive of this package is driven by https://github.com/gatsbyjs/gatsby/pull/6550

here's why I hesitate to contribute it back to `opn`:

> @m-allanson I think reuseing the same tab is really a web development specific thing, e.g. http://localhost:8000 and opn isn’t just for opening an URL in browser, it also supprts stuffs like image, text file and more options.

_Originally posted by @ExiaSR in https://github.com/gatsbyjs/gatsby/pull/6550#issuecomment-406315418_ 

that said, I am definitely open to contribute back to upstream

**Comment by karlhorky** [comment]
> I am definitely open to contribute back to upstream if there is need

@sindresorhus actually mentioned in https://github.com/sindresorhus/open/issues/31 (emphasis mine):

> You could probably use AppleScript to achieve what you want, but **that's way out of scope for this module**.

[I've asked](https://github.com/sindresorhus/open/issues/31#issuecomment-521671393) if this is still the status quo.

---

> reuseing the same tab is really a web development specific thing
> opn isn’t just for opening an URL in browser, it also supprts stuffs like image, text file and more options

Ah interesting, good points.

Then I guess for this reason I would suggest renaming this module to something that doesn't infer that this is a superset of the other module ("better"). For me it was confusing, at least.

What I would see as a good angle would be to market it as a standalone (zero dependency) version of `react-dev-utils/openBrowser`. The following code works well, but it [has problems with dependency hell](https://github.com/facebook/create-react-app/issues/7068).

```js
const openBrowser = require('react-dev-utils/openBrowser');
openBrowser('http://localhost:6006');
```
